"""cria extratos

Revision ID: b7f0a3c1de22
Revises: acf343d89740
Create Date: 2026-09-09 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7f0a3c1de22"
down_revision: str | None = "acf343d89740"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extratos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("nome_arquivo", sa.String(), nullable=False),
        sa.Column("formato", sa.String(length=3), nullable=False),
        sa.Column("tamanho_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), server_default="pendente", nullable=False),
        sa.Column("quantidade_lancamentos", sa.Integer(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("formato IN ('ofx', 'csv')", name="ck_extratos_formato_suportado"),
        sa.CheckConstraint(
            "status IN ('pendente', 'processando', 'concluido', 'erro')",
            name="ck_extratos_status_valido",
        ),
        sa.ForeignKeyConstraint(
            ["empresa_id"],
            ["empresas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_extratos_empresa_id"), "extratos", ["empresa_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_extratos_empresa_id"), table_name="extratos")
    op.drop_table("extratos")
    # ### end Alembic commands ###
