"""indices em lancamentos (extrato_id, data, valor)

Revision ID: cbe4497d857c
Revises: fdeeba077c27
Create Date: 2026-09-21 10:44:27.687469

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbe4497d857c"
down_revision: str | None = "fdeeba077c27"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_lancamentos_data"), "lancamentos", ["data"], unique=False)
    op.create_index(op.f("ix_lancamentos_extrato_id"), "lancamentos", ["extrato_id"], unique=False)
    op.create_index(op.f("ix_lancamentos_valor"), "lancamentos", ["valor"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lancamentos_valor"), table_name="lancamentos")
    op.drop_index(op.f("ix_lancamentos_extrato_id"), table_name="lancamentos")
    op.drop_index(op.f("ix_lancamentos_data"), table_name="lancamentos")
    # ### end Alembic commands ###
