"""cria lancamentos

Revision ID: ce807ddb70c1
Revises: b7f0a3c1de22
Create Date: 2026-09-15 19:26:15.947100

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce807ddb70c1"
down_revision: str | None = "b7f0a3c1de22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lancamentos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("empresa_id", sa.UUID(), nullable=False),
        sa.Column("extrato_id", sa.UUID(), nullable=False),
        sa.Column("data", sa.Date(), nullable=False),
        sa.Column("valor", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("descricao", sa.String(), nullable=False),
        sa.Column("tipo", sa.String(), nullable=False),
        sa.Column("hash_dedup", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("tipo IN ('credito', 'debito')", name="ck_lancamentos_tipo_valido"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id"]),
        sa.ForeignKeyConstraint(["extrato_id"], ["extratos.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "empresa_id", "extrato_id", "hash_dedup", name="uq_lancamentos_empresa_extrato_hash"
        ),
    )
    op.create_index(op.f("ix_lancamentos_empresa_id"), "lancamentos", ["empresa_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_lancamentos_empresa_id"), table_name="lancamentos")
    op.drop_table("lancamentos")
    # ### end Alembic commands ###
