"""cria linhas invalidas e adiciona concluido_com_erros ao status de extratos

Revision ID: fdeeba077c27
Revises: ce807ddb70c1
Create Date: 2026-09-15 20:16:21.297045

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdeeba077c27"
down_revision: str | None = "ce807ddb70c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linhas_invalidas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extrato_id", sa.UUID(), nullable=False),
        sa.Column("identificador", sa.String(), nullable=False),
        sa.Column("motivo", sa.String(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["extrato_id"], ["extratos.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_linhas_invalidas_extrato_id"), "linhas_invalidas", ["extrato_id"], unique=False
    )
    # ### end Alembic commands ###

    # Autogenerate não detecta mudança de texto de CheckConstraint — feito
    # a mão: adiciona 'concluido_com_erros' à lista de status válidos de
    # extratos (issue #13, ver app/models/extrato.py).
    op.drop_constraint("ck_extratos_status_valido", "extratos", type_="check")
    op.create_check_constraint(
        "ck_extratos_status_valido",
        "extratos",
        "status IN ('pendente', 'processando', 'concluido', 'concluido_com_erros', 'erro')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_extratos_status_valido", "extratos", type_="check")
    op.create_check_constraint(
        "ck_extratos_status_valido",
        "extratos",
        "status IN ('pendente', 'processando', 'concluido', 'erro')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_linhas_invalidas_extrato_id"), table_name="linhas_invalidas")
    op.drop_table("linhas_invalidas")
    # ### end Alembic commands ###
